# Generated by Django 4.0.5 on 2022-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
